# Generated by Django 5.1.3 on 2025-03-19 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heaven', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact_Us',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('query', models.CharField(max_length=20)),
                ('member', models.CharField(default='No', max_length=5)),
                ('writer', models.CharField(default='No', max_length=5)),
                ('reader', models.CharField(default='No', max_length=5)),
                ('concern', models.TextField()),
            ],
        ),
    ]
