# Generated by Django 5.1.3 on 2025-03-19 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('heaven', '0002_contact_us'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact_us',
            name='member',
        ),
    ]
