# Generated by Django 5.1.3 on 2025-03-19 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heaven', '0003_remove_contact_us_member'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact_us',
            name='reader',
            field=models.CharField(blank=True, default='No', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='contact_us',
            name='writer',
            field=models.CharField(blank=True, default='No', max_length=5, null=True),
        ),
    ]
